name: WebRTC C SDK CI

on:
  push:
    branches:
      - test-mips-qemu-develop
  pull_request:
    branches:
      - develop
      - master
jobs:
  mips-cross-compilation:
    runs-on: ubuntu-18.04
    env:
      CC: gcc-mips-linux-gnu
      CXX: g++-mips-linux-gnu
      AWS_KVS_LOG_LEVEL: 2
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: mips64
      - name: Install dependencies
        run: | 
          sudo apt-get update -y
          sudo apt-get -y install gcc-mips-linux-gnu g++-mips-linux-gnu binutils-mips-linux-gnu
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build Repository
        run: |
          sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
          mkdir build && cd build
          cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=mips64-unknown-linux-gnu
          make
